### ISSUE TITLE
undefined reference to '__csan_FUNC'

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/infrastructure#10]
As noted in the README, these are known about, but should be reported.
I found that I was triggering this with `unlink`,`realpath`, and `readlink`

I got these while trying to build https://github.com/wheatman/mold/tree/cilk with `-fsanitize=cilk`

Let me know if you need anything else.

**Comment by neboat** [comment]
This issue has been fixed in the latest release of OpenCilk.
