### ISSUE TITLE
Cannot build on Intel(R) Core(TM) i7-4770

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/infrastructure#24]
I was trying to build opencilk on an old machine and got the following error 
```
/home/wheatman/opencilk/opencilk/compiler-rt/lib/builtins/fp_extend.h:44:9: error: ‘_Float16’ is not supported on this target
```

Is _Float16 necessary, or can it be avoided with some flag

The machine in question is a Haswell, which I thought was new enough. 

```
lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    CPU family:          6
    Model:               60
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            3
    CPU(s) scaling MHz:  20%
    CPU max MHz:         3900.0000
    CPU min MHz:         800.0000
    BogoMIPS:            6784.52
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx f
                         xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_
                         good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx e
                         st tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c
                          rdrand lahf_lm abm cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid e
                         pt_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt dtherm ida arat pl
                         n pts
Virtualization features:
  Virtualization:        VT-x
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    1 MiB (4 instances)
  L3:                    8 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-7
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
  Mds:                   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling
  Srbds:                 Vulnerable: No microcode
  Tsx async abort:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
```
```
cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Thirty Six)"
```

**Comment by wheatman** [comment]
I tried to confirm if this was an issue with opencilk, or just one with llvm-14, and so I built llvm 14 on the same machine with the following cmake command which I tried to make similar to the one used in opencilk, so let me know if there is a better command I can use to test if the issue also arises here. 
`cmake -S llvm -B build -G "Unix Makefiles" LLVM_ENABLE_PROJECTS="clang;compiler-rt" -DCMAKE_BUILD_TYPE=Release ../llvm`

I was on the branch release/14.x commit f28c006a5895fc0e329fe15fead81e37457cb1d1

**Comment by neboat** [comment]
I just ran a test of building OpenCilk from source (using this scripts in this repo) on a machine I have with the same processor, a Core i7-4770.  The build completed without issue.

At a guess, check that your system has matching versions of `gcc` and `g++`.  System configuration issues, like mismatched compiler versions, can lead to strange failures during the build process.  Right now that's what I suspect is going wrong on your end.

As for the test of building vanilla LLVM from source on the same system, I'm not sure if it's a typo, but you need `-DLLVM_ENABLE_PROJECTS="clang;compiler-rt"` in your `cmake` configure command, not just `LLVM_ENABLE_PROJECTS="clang;compiler-rt".

**Comment by wheatman** [comment]
Yeah, I did have a typo in the cmake line for base clang, which means that the issue was in base llvm, not opencilk, thanks for seeing that.  I'm not sure what it is, they are both using g++/gcc 12.1.1, but I will look into that

**Comment by wheatman** [comment]
The issue was related to https://discourse.llvm.org/t/how-to-build-compiler-rt-for-new-x86-half-float-abi/63366/4

I leave the solution I used here in case anybody else runs into this
I added `CFLAGS=-msse2 CXXFLAGS=-msse2` to the cmake configuration line in infrastructure/tools/build

The end line ended up being 

```
CFLAGS=-msse2 CXXFLAGS=-msse2 cmake -DLLVM_ENABLE_PROJECTS="${COMPONENTS}" \
      -DLLVM_ENABLE_RUNTIMES="${RUNTIMES}" \
      -DLLVM_ENABLE_ASSERTIONS="${OPENCILK_ASSERTIONS:?}" \
      -DLLVM_TARGETS_TO_BUILD="${TARGETS:?}" \
      -DCMAKE_BUILD_TYPE="${OPENCILK_RELEASE:?}" \
      -DCMAKE_INSTALL_PREFIX="${OPENCILK_INSTALL_PREFIX:?}" \
      -DLLVM_OPTIMIZED_TABLEGEN=On \
      "${OPENCILK_SOURCE}/llvm"
```
