### ISSUE TITLE
Compile error on ubuntu 22.04  

### ISSUE THREAD

**Issue by AndyWyy** [OpenCilk/infrastructure#27]
I get the source code of Opencilk-1.0 and my gcc/g++ version is 7.5
I get these errors when compiling.
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/56649489/221166005-0be892dc-f6c1-4d1d-b73e-09da27daab7c.png">
The Readme file of the repo says "This error typically occurs when the C and C++ compilers on the system are mismatched"
But I'm sure that my C and C++ compilers have the same version, I wonder how can I solve these problems .
Thanks a lot!

**Comment by neboat** [comment]
There should be a `CMakeCache.txt` file inside your build directory.  Can you look at that file and tell me what entries it contains for `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`?

**Comment by AndyWyy** [comment]
> There should be a `CMakeCache.txt` file inside your build directory. Can you look at that file and tell me what entries it contains for `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`?

Thanks for your answer. But I've already rollback my system to ubuntu 20.04 and I have no backup files.
At present, opencilk1.0 has no problems on ubuntu 20.04, so I'll close this issue
