### ISSUE TITLE
CentOS support for Performance Evaluation runs

### ISSUE THREAD

**Issue by gonidelis** [OpenCilk/infrastructure#8]
Hello!

I am trying to run some performance evaluation experiments by comparing Cilk/openCilk against C++ Standard Algorithms solutions as part of my thesis under the supervision of prof. Pitsianis. The experiments will be held on a remote node given the demand for high computation capabilities. 

What's the best openCilk installation option for a CentOS 8.2 system? Is there any way to avoid source installation?

**Comment by neboat** [comment]
We don't distribute precompiled binaries for CentOS.

I recommend following the "Quick Start" instructions for building OpenCilk 1.0 from source: https://github.com/OpenCilk/infrastructure/blob/release/INSTALLING.md#quick-start.

Alternatively, if Docker is installed on your system and you're comfortable using Docker for your experiments, then you can try using the OpenCilk Docker image.  That Docker image is available here: https://github.com/OpenCilk/opencilk-project/releases/download/opencilk%2Fv1.0/docker-opencilk-v1.0.tar.gz

**Comment by gonidelis** [comment]
@neboat Thanks a lot for the quick response!
